### ISSUE TITLE
About Page - 403 Forbidden

### ISSUE THREAD

**Issue by coderwill** [hyperledger/hyperledger-web#2]
Hello, congrats on the acquisition - just a quick heads up that it appears the permissions are set incorrectly on the [About Page](http://hyperledger.com/about.html) which is resulting in a 403 Forbidden error whenever it gets requested.

**Comment by danoprey** [comment]
Thanks a lot!

And thanks for pointing that out. Not sure how only that page was affected. Fixed now, although may need a cache clear: http://hyperledger.com/about.html?fixed

**Comment by coderwill** [comment]
@danoprey No prob, you're welcome - have a nice weekend!
